// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:devsolutions_task/features/home/domain/entities/product_entity.dart';
import 'package:devsolutions_task/features/home/domain/entities/rating_entity.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ProductEntityAdapter());
    registerAdapter(RatingEntityAdapter());
  }
}
